version: '3.7'
services:
  app:
    build: .
    command: 
      - jekyll serve --force_polling
      - mkdir /root/.ssh
      - apk add openssh
      - chmod 600 /root/.ssh/*
      - touch Gemfile.lock
      - chmod 777  /workspace/panthera-jekyll/*
      # - USER_ID=${LOCAL_UID:-9001}
      # - GROUP_ID=${LOCAL_GID:-9001}
      # - useradd -u $USER_ID -o -m user
      # - groupmod -g $GROUP_ID user
      # - export HOME=/home/user

    volumes:
      - .:/srv/jekyll
      - ${USERPROFILE}\\.ssh_docker:/root/.ssh
    ports:
      - 4000:4000   
    
    